name: Build

on: [push]

jobs:
  Build:

    # Use cutting-edge Ubuntu to get rsvg-convert 2.52.x, which fixes a
    # showstopper bug in the 2.48.x version used by ubuntu-current.
    runs-on: ubuntu-22.04
    steps:

      # Checkout the code.
    - name: Checkout
      uses: actions/checkout@v3

      # Install the dependencies.
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install librsvg2-bin
        sudo apt install pngcrush

      # Generate the output images.
    - name: Generate outputs
      run: make

      # Create the release ID from the repo name and version tag.
    - name: Release - get ID
      id: get-id
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        project=$(echo "${{github.repository}}" | cut -d/ -f2)
        version=$(echo "${{github.ref_name}}" | sed 's/^v//')
        echo "::set-output name=id::${project}-${version}"

      # Package the release artifacts.
    - name: Release - package artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mv out ${{steps.get-id.outputs.id}}
        tar cvzf ${{steps.get-id.outputs.id}}.tar.gz ${{steps.get-id.outputs.id}}

      # Create a release.
    - name: Release - create
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: ${{steps.get-id.outputs.id}}
        files: |
          ${{steps.get-id.outputs.id}}.tar.gz
